# Site settings
title: 'Nice Shot' # Your Title
tagline: 'To find something interesting ' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/